# Generated by Django 3.0.4 on 2020-04-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Date du repas')),
                ('pseudo', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
