# Generated by Django 3.0.4 on 2020-06-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0002_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'profil'},
        ),
    ]
