# Generated by Django 3.0.4 on 2020-06-02 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partage_repas', '0007_auto_20200601_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repas',
            name='pseudo',
        ),
        migrations.AddField(
            model_name='repas',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
