# Generated by Django 3.0.4 on 2020-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0008_auto_20200602_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repas',
            name='utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
