# Generated by Django 3.0.4 on 2020-06-02 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partage_repas', '0009_auto_20200602_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repas',
            name='date',
            field=models.DateTimeField(help_text='jj/mm/aaaa', verbose_name='Date du repas'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repas', models.ManyToManyField(to='partage_repas.Repas', verbose_name='liste de repas')),
                ('utilisateur', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name="liste d'users")),
            ],
        ),
    ]
