# Generated by Django 3.0.4 on 2020-06-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0012_auto_20200602_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='mesrepas',
        ),
        migrations.AddField(
            model_name='repas',
            name='participants',
            field=models.ManyToManyField(to='partage_repas.Profil'),
        ),
    ]
