# Generated by Django 3.0.4 on 2020-06-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0013_auto_20200602_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('repas', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='repas',
            name='participants',
        ),
    ]
