# Generated by Django 3.0.4 on 2020-06-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0014_auto_20200603_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrit',
            old_name='repas',
            new_name='idrepas',
        ),
    ]
