# Generated by Django 3.0.4 on 2020-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0015_auto_20200603_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='repas',
            name='dejainscrit',
            field=models.BooleanField(default=False),
        ),
    ]
