# Generated by Django 3.0.4 on 2020-06-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0019_auto_20200603_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
