# Generated by Django 3.0.4 on 2020-06-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0020_profil_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='test',
        ),
    ]
