# Generated by Django 3.0.4 on 2020-06-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0021_remove_profil_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
