# Generated by Django 3.0.4 on 2020-06-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0022_delete_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('valeur', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='repas',
            name='dejainscrit',
        ),
    ]
