# Generated by Django 3.0.4 on 2020-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0023_auto_20200604_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='repas',
            name='allergene',
            field=models.CharField(choices=[('L', 'lait'), ('O', 'oeuf'), ('CM', 'Crustacé-Mollusque'), ('N', 'Noix')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='repas',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='repas',
            name='regime',
            field=models.CharField(choices=[('C', 'Classique'), ('H', 'Halal'), ('VR', 'Végétarien'), ('VL', 'Végétalien'), ('GF,', 'GlutenFree')], default='C', max_length=3),
        ),
    ]
