# Generated by Django 3.0.4 on 2020-06-05 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0024_auto_20200605_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repas',
            name='allergene',
            field=models.CharField(choices=[('L', 'Lait'), ('O', 'Oeuf'), ('CM', 'Crustacé-Mollusque'), ('N', 'Noix')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='partage_repas.Repas')),
            ],
        ),
    ]
