# Generated by Django 3.0.4 on 2020-06-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0027_auto_20200605_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repas',
            name='allergene',
            field=models.CharField(choices=[('Lait', 'Lait'), ('Oeuf', 'Oeuf'), ('Crustacé-Mollusque', 'Crustacé-Mollusque'), ('Noix', 'Noix')], max_length=100, null=True),
        ),
    ]
