# Generated by Django 3.0.4 on 2020-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0029_auto_20200605_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentaire',
            field=models.TextField(default='Super repas'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pseudo',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
