# Generated by Django 3.0.4 on 2020-06-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0030_auto_20200605_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repas',
            name='allergene',
            field=models.CharField(default='Aucun', help_text='Les allergènes courant sont le lait, les oeufs, les crustacées, les noix', max_length=100),
        ),
    ]
