# Generated by Django 3.0.4 on 2020-06-07 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partage_repas', '0031_auto_20200606_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pseudo',
            field=models.ForeignKey(db_column='pseudo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repas',
            name='allergene',
            field=models.CharField(default='Aucun', help_text='Les allergènes courants sont le lait, les oeufs, les crustacées, les noix', max_length=100, verbose_name='Allergènes'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='date',
            field=models.DateTimeField(help_text='jj/mm/aaaa hh:mm', verbose_name='Date et heure du repas'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='moyen_de_contact',
            field=models.TextField(default='', help_text='Ce champ sera visible uniquement par les personnes inscrites au repas', verbose_name='Comment me contacter'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='nombre_participant',
            field=models.PositiveIntegerField(verbose_name='Nombre maximal de participants'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(models.DecimalField(verbose_name='0.10'))], verbose_name='Prix de participation'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='regime',
            field=models.CharField(choices=[('Classique', 'Classique'), ('Halal', 'Halal'), ('Végétarien', 'Végétarien'), ('Végétalien', 'Végétalien'), ('Sans Gluten,', 'Sans Gluten')], default='Classique', max_length=100, verbose_name='Régime alimentaire'),
        ),
    ]
