# Generated by Django 3.0.4 on 2020-06-07 13:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partage_repas', '0032_auto_20200607_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repas',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Prix de participation'),
        ),
    ]
